import pa

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("Ecommerce.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Id       52 non-null     int64
 1   Gender   52 non-null     object
 2   Country  52 non-null     object
 3   Amount   52 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.8+ KB

In [7]:
gc= df.groupby("Country")
gc.groups

{'KSA': [0, 1, 2, 4, 5, 9, 17, 33, 37, 39, 40, 41, 42, 44, 46, 47, 49, 50, 51], 'Kuwait': [3, 6, 11, 15, 16, 18, 19, 23, 26, 30, 31, 32, 34, 35, 36, 38, 43, 48], 'UAE': [7, 8, 10, 12, 13, 14, 20, 21, 22, 24, 25, 27, 28, 29, 45]}

In [8]:
gc.get_group('KSA')

    Id  Gender Country  Amount
0    1    male     KSA    1500
1    2    male     KSA    2000
2    3    male     KSA    3000
4    5  female     KSA    1000
5    6    male     KSA    1500
9   10  female     KSA    1000
17  18    male     KSA    3000
33  34    male     KSA    2000
37  38  female     KSA    1000
39  40  female     KSA    1500
40  41  female     KSA    2000
41  42  female     KSA    1000
42  43  female     KSA    1500
44  45  female     KSA    3000
46  47  female     KSA    1000
47  48  female     KSA    1500
49  50  female     KSA    3000
50  51  female     KSA    1500
51  52  female     KSA    2000

In [9]:
gc= df.groupby(['Country','Gender'])
for name,gender in gc:
    print(name)
    print(gender)

('KSA', 'female')
    Id  Gender Country  Amount
4    5  female     KSA    1000
9   10  female     KSA    1000
37  38  female     KSA    1000
39  40  female     KSA    1500
40  41  female     KSA    2000
41  42  female     KSA    1000
42  43  female     KSA    1500
44  45  female     KSA    3000
46  47  female     KSA    1000
47  48  female     KSA    1500
49  50  female     KSA    3000
50  51  female     KSA    1500
51  52  female     KSA    2000
('KSA', 'male')
    Id Gender Country  Amount
0    1   male     KSA    1500
1    2   male     KSA    2000
2    3   male     KSA    3000
5    6   male     KSA    1500
17  18   male     KSA    3000
33  34   male     KSA    2000
('Kuwait', 'female')
    Id  Gender Country  Amount
3    4  female  Kuwait    2000
11  12  female  Kuwait    2000
18  19  female  Kuwait    2000
35  36  female  Kuwait    1000
36  37  female  Kuwait    2000
38  39  female  Kuwait    3000
43  44  female  Kuwait    2000
48  49  female  Kuwait    2000
('Kuwait', 'male')
    Id Gender Country  Amount
6    7   male  Kuwait    2000
15  16   male  Kuwait    1500
16  17   male  Kuwait    2000
19  20   male  Kuwait    1000
23  24   male  Kuwait    1000
26  27   male  Kuwait    1500
30  31   male  Kuwait    1500
31  32   male  Kuwait    1000
32  33   male  Kuwait    1500
34  35   male  Kuwait    1000
('UAE', 'female')
    Id  Gender Country  Amount
10  11  female     UAE    1500
12  13  female     UAE    3000
14  15  female     UAE    1000
45  46  female     UAE    1500
('UAE', 'male')
    Id Gender Country  Amount
7    8   male     UAE    3000
8    9   male     UAE    2000
13  14   male     UAE    2000
20  21   male     UAE    3000
21  22   male     UAE    1500
22  23   male     UAE    3000
24  25   male     UAE    2000
25  26   male     UAE    1000
27  28   male     UAE    3000
28  29   male     UAE    2000
29  30   male     UAE    1000

In [12]:
gc= df.groupby("Country")['Id'].count()
gc

Country
KSA       19
Kuwait    18
UAE       15
Name: Id, dtype: int64

In [14]:
gc= df.groupby(['Country','Gender']).count()
gc

                Id  Amount
Country Gender
KSA     female  13      13
        male     6       6
Kuwait  female   8       8
        male    10      10
UAE     female   4       4
        male    11      11

In [18]:
gc= df.groupby("Country")['Amount'].mean()
gc

Country
KSA       1789.473684
Kuwait    1666.666667
UAE       2033.333333
Name: Amount, dtype: float64

In [23]:
gc= df.groupby(['Country']).agg(Mean_Amount=("Amount","mean"),Sum=("Amount","sum"),numbers=("Id","count"))
gc

         Mean_Amount    Sum  numbers
Country
KSA      1789.473684  34000       19
Kuwait   1666.666667  30000       18
UAE      2033.333333  30500       15