In [3]:
import pandas as pd

In [5]:
df1 =pd.DataFrame({'city':['A','B','C',],
                   'day1':[22,5,28],
                   'day2':[10,14,15],
                   'day3':[33,44,5],
                   'day4':[55,62,79],
                   'day5':[11,33,55]})
df1

  city  day1  day2  day3  day4  day5
0    A    22    10    33    55    11
1    B     5    14    44    62    33
2    C    28    15     5    79    55

In [6]:
df1.melt(id_vars=['city'])

   city variable  value
0     A     day1     22
1     B     day1      5
2     C     day1     28
3     A     day2     10
4     B     day2     14
5     C     day2     15
6     A     day3     33
7     B     day3     44
8     C     day3      5
9     A     day4     55
10    B     day4     62
11    C     day4     79
12    A     day5     11
13    B     day5     33
14    C     day5     55

In [8]:
df1.melt(id_vars=['city'], var_name='date',value_name='temprature')

   city  date  temprature
0     A  day1          22
1     B  day1           5
2     C  day1          28
3     A  day2          10
4     B  day2          14
5     C  day2          15
6     A  day3          33
7     B  day3          44
8     C  day3           5
9     A  day4          55
10    B  day4          62
11    C  day4          79
12    A  day5          11
13    B  day5          33
14    C  day5          55

In [11]:
df1.melt(id_vars=['city'], var_name='date',value_name='temprature').sort_values(by='city')

   city  date  temprature
0     A  day1          22
3     A  day2          10
6     A  day3          33
9     A  day4          55
12    A  day5          11
1     B  day1           5
4     B  day2          14
7     B  day3          44
10    B  day4          62
13    B  day5          33
2     C  day1          28
5     C  day2          15
8     C  day3           5
11    C  day4          79
14    C  day5          55

In [12]:
df1.melt(id_vars=['city'], var_name='date',value_name='temprature').sort_values(by='city').reset_index(drop=True)

   city  date  temprature
0     A  day1          22
1     A  day2          10
2     A  day3          33
3     A  day4          55
4     A  day5          11
5     B  day1           5
6     B  day2          14
7     B  day3          44
8     B  day4          62
9     B  day5          33
10    C  day1          28
11    C  day2          15
12    C  day3           5
13    C  day4          79
14    C  day5          55