In [2]:
import pandas as pd

In [5]:
df= pd.read_csv("Students_exams.csv")
df.head()

   gender  math score  reading score  writing score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

In [6]:
gender =df["gender"]
gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [8]:
mathscore =df["math score"]
mathscore

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [11]:
Student =df[["math score","gender"]]
Student

     math score  gender
0            72  female
1            69  female
2            90  female
3            47    male
4            76    male
..          ...     ...
995          88  female
996          62    male
997          59  female
998          68  female
999          77  female

[1000 rows x 2 columns]

In [12]:
rows =df[3:7]
rows

   gender  math score  reading score  writing score
3    male          47             57             44
4    male          76             78             75
5  female          71             83             78
6  female          88             95             92

In [13]:
result =df.loc[0]
result

gender           female
math score           72
reading score        72
writing score        74
Name: 0, dtype: object

In [15]:
result =df.loc[[0,2,999]]

result

     gender  math score  reading score  writing score
0    female          72             72             74
2    female          90             95             93
999  female          77             86             86

In [18]:
result =df.loc[[0,3,],['gender']]
result

   gender
0  female
3    male

In [19]:
result =df.loc[:,['gender']]
result

     gender
0    female
1    female
2    female
3      male
4      male
..      ...
995  female
996    male
997  female
998  female
999  female

[1000 rows x 1 columns]

In [21]:
result =df.loc[15:30,['gender']]
result

    gender
15  female
16    male
17  female
18    male
19  female
20    male
21  female
22    male
23  female
24    male
25    male
26    male
27  female
28    male
29  female
30  female

In [22]:
df

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [23]:
result =df.iloc[0]
result

gender           female
math score           72
reading score        72
writing score        74
Name: 0, dtype: object

In [25]:
result =df.iloc[[1,999],[0,3]]
result

     gender  writing score
1    female             88
999  female             86