In [4]:
import pandas as pd

In [6]:
df =pd.read_csv("Students_exams_error.csv")
df.head()

   gender math score  reading score  writing score
0  female         72           72.0           74.0
1     NaN         69           90.0           88.0
2  female         90           95.0           93.0
3    male         47            NaN           44.0
4    male        abc            NaN           75.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         998 non-null    object
 1   math score     1000 non-null   object
 2   reading score  997 non-null    float64
 3   writing score  997 non-null    float64
dtypes: float64(2), object(2)
memory usage: 31.4+ KB

In [9]:
df.isnull()

     gender  math score  reading score  writing score
0     False       False          False          False
1      True       False          False          False
2     False       False          False          False
3     False       False           True          False
4     False       False           True          False
..      ...         ...            ...            ...
995   False       False          False          False
996   False       False          False          False
997   False       False          False          False
998   False       False          False          False
999   False       False          False          False

[1000 rows x 4 columns]

In [10]:
df.isnull()

<bound method DataFrame.sum of      gender  math score  reading score  writing score
0     False       False          False          False
1      True       False          False          False
2     False       False          False          False
3     False       False           True          False
4     False       False           True          False
..      ...         ...            ...            ...
995   False       False          False          False
996   False       False          False          False
997   False       False          False          False
998   False       False          False          False
999   False       False          False          False

[1000 rows x 4 columns]>

In [ ]:
df.isnull().sum()