In [1]:
import pandas as pd
df =pd.read_csv("Students_exams_cols_cleanup.csv")
df.head()

   Gender  Math Score  Reading Score  Writing Score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

In [2]:
df.columns

Index(['Gender', 'Math Score', 'Reading Score', 'Writing Score'], dtype='object')

In [4]:
df.columns= [col.lower() for col in df]
df.columns

Index(['gender', 'math score', 'reading score', 'writing score'], dtype='object')

In [8]:
df.rename(columns={
    'math score':'math_score',
    'reading score':'reading_score',
     'writing score': 'writing_score',
},inplace=True
)
df

     gender  math_score  reading_score  writing_score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]