In [10]:
import  pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [11]:
df1=pd.read_csv("Sales/Sales_April_2019.csv")
df1["month"]="apr"

df2=pd.read_csv("Sales/Sales_August_2019.csv")
df2["month"]="aug"

df3=pd.read_csv("Sales/Sales_December_2019.csv")
df3["month"]="dec"

df4=pd.read_csv("Sales/Sales_February_2019.csv")
df4["month"]="feb"

df5=pd.read_csv("Sales/Sales_January_2019.csv")
df5["month"]="jan"

df6=pd.read_csv("Sales/Sales_July_2019.csv")
df6["month"]="jul"

df7=pd.read_csv("Sales/Sales_June_2019.csv")
df7["month"]="jun"

df8=pd.read_csv("Sales/Sales_March_2019.csv")
df8["month"]="mar"

df9=pd.read_csv("Sales/Sales_May_2019.csv")
df9["month"]="may"

df10=pd.read_csv("Sales/Sales_November_2019.csv")
df10["month"]="nov"

df11=pd.read_csv("Sales/Sales_October_2019.csv")
df11["month"]="oct"

df12=pd.read_csv("Sales/Sales_September_2019.csv")
df12["month"]="sep"

In [12]:
list=[df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12]

In [13]:
for i in list:
    print(i.shape)

(18383, 7)
(12011, 7)
(25117, 7)
(12036, 7)
(9723, 7)
(14371, 7)
(13622, 7)
(15226, 7)
(16635, 7)
(17661, 7)
(20379, 7)
(11686, 7)

In [14]:
frame= pd.concat(list,ignore_index=True)
frame

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,month
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",apr
1,NaN,NaN,NaN,NaN,NaN,NaN,apr
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",apr
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",apr
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",apr
...,...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",sep
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",sep
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",sep
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",sep
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",sep

In [6]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186850 entries, 0 to 186849
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186305 non-null  object
 1   Product           186305 non-null  object
 2   Quantity Ordered  186305 non-null  object
 3   Price Each        186305 non-null  object
 4   Order Date        186305 non-null  object
 5   Purchase Address  186305 non-null  object
 6   month             186850 non-null  object
dtypes: object(7)
memory usage: 10.0+ MB

In [15]:
frame.isnull().sum()

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
month                 0
dtype: int64

In [16]:
frame.duplicated().sum()

np.int64(1140)

In [33]:
frame.unique().sum()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [18]:
frame["Product"].unique()

array(['USB-C Charging Cable', nan, 'Bose SoundSport Headphones',
       'Google Phone', 'Wired Headphones', 'Macbook Pro Laptop',
       'Lightning Charging Cable', '27in 4K Gaming Monitor',
       'AA Batteries (4-pack)', 'Apple Airpods Headphones',
       'AAA Batteries (4-pack)', 'iPhone', 'Flatscreen TV',
       '27in FHD Monitor', '20in Monitor', 'LG Dryer', 'ThinkPad Laptop',
       'Vareebadd Phone', 'LG Washing Machine', '34in Ultrawide Monitor',
       'Product'], dtype=object)

In [19]:
frame.columns= [col.lower() for col in frame]
frame

,order id,product,quantity ordered,price each,order date,purchase address,month
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",apr
1,NaN,NaN,NaN,NaN,NaN,NaN,apr
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",apr
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",apr
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",apr
...,...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",sep
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",sep
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",sep
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",sep
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",sep

In [20]:
frame.rename(columns={"	order id":"	order_id",
              "quantity ordered":"quantity_ordered",
              "price each":"price_each",
              "order date":"order_date",
              "purchase address":"purchase_address",
             },inplace=True
)
frame

,order id,product,quantity_ordered,price_each,order_date,purchase_address,month
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",apr
1,NaN,NaN,NaN,NaN,NaN,NaN,apr
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",apr
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",apr
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",apr
...,...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",sep
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",sep
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",sep
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",sep
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",sep

In [21]:
(frame.isnull().sum().sum())/len(frame)*100

np.float64(1.75006689858175)

In [22]:
frame= frame.dropna()
frame.isnull().sum()

order id            0
product             0
quantity_ordered    0
price_each          0
order_date          0
purchase_address    0
month               0
dtype: int64

In [23]:
frame= frame.astype({"quantity_ordered":int,"price_each":float})

ValueError: invalid literal for int() with base 10: 'Quantity Ordered': Error while type casting for column 'quantity_ordered'

In [25]:
frame["quantity_ordered"].unique()

array(['2', '1', '3', '5', 'Quantity Ordered', '4', '7', '6', '8', '9'],
      dtype=object)

In [26]:
frame["price_each"].unique()

array(['11.95', '99.99', '600', '11.99', '1700', '14.95', '389.99',
       '3.84', '150', '2.99', '700', '300', '149.99', '109.99', '600.0',
       '999.99', '400', '379.99', 'Price Each', '700.0', '1700.0',
       '150.0', '300.0', '400.0'], dtype=object)

In [27]:
df = frame[frame["quantity_ordered"] != "Quantity Ordered"]

In [28]:
df=frame[frame["price_each"] != "Price Each"]

In [29]:
df["price_each"].unique()

array(['11.95', '99.99', '600', '11.99', '1700', '14.95', '389.99',
       '3.84', '150', '2.99', '700', '300', '149.99', '109.99', '600.0',
       '999.99', '400', '379.99', '700.0', '1700.0', '150.0', '300.0',
       '400.0'], dtype=object)

In [30]:
df["quantity_ordered"].unique()

array(['2', '1', '3', '5', '4', '7', '6', '8', '9'], dtype=object)

In [36]:
df= df.astype({"quantity_ordered":int,"price_each":float})

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185950 entries, 0 to 186849
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order id          185950 non-null  object
 1   product           185950 non-null  object
 2   quantity_ordered  185950 non-null  object
 3   price_each        185950 non-null  object
 4   order_date        185950 non-null  object
 5   purchase_address  185950 non-null  object
 6   month             185950 non-null  object
dtypes: object(7)
memory usage: 11.3+ MB

In [37]:
df["sales"] =df["quantity_ordered"] *df["price_each"]
df

,order id,product,quantity_ordered,price_each,order_date,purchase_address,month,sales
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",apr,23.90
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",apr,99.99
3,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",apr,600.00
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",apr,11.99
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",apr,11.99
...,...,...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",sep,8.97
186846,259354,iPhone,1,700.00,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",sep,700.00
186847,259355,iPhone,1,700.00,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",sep,700.00
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",sep,379.99
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",sep,11.95