In [1]:
import pandas as pd

In [2]:
df= pd.read_json('movies.json')
df

,title,year,cast,genres
0,After Dark in Central Park,1900,[],[]
1,Boarding School Girls' Pajama Parade,1900,[],[]
2,Buffalo Bill's Wild West Parad,1900,[],[]
3,Caught,1900,[],[]
4,Clowns Spinning Hats,1900,[],[]
...,...,...,...,...
28790,Bumblebee,2018,"[Hailee Steinfeld, John Cena, Jorge Lendeborg ...","[Action, Adventure, Science Fiction]"
28791,Welcome to Marwen,2018,"[Steve Carell, Leslie Mann, Diane Kruger, Falk...","[Fantasy, Drama]"
28792,Holmes and Watson,2018,"[Will Ferrell, John C. Reilly, Rebecca Hall, R...","[Action, Mystery, Comedy]"
28793,On the Basis of Sex,2018,"[Felicity Jones, Armie Hammer, Justin Theroux,...","[Biography, Drama]"
28794,Destroyer,2018,"[Nicole Kidman, Tatiana Maslany, Sebastian Sta...","[Crime, Thriller]"

In [4]:
df.shape

(28795, 4)

In [5]:
 df.head()

                                  title  year cast genres
0            After Dark in Central Park  1900   []     []
1  Boarding School Girls' Pajama Parade  1900   []     []
2        Buffalo Bill's Wild West Parad  1900   []     []
3                                Caught  1900   []     []
4                  Clowns Spinning Hats  1900   []     []

In [6]:
df.tail()

,title,year,cast,genres
28790,Bumblebee,2018,"[Hailee Steinfeld, John Cena, Jorge Lendeborg ...","[Action, Adventure, Science Fiction]"
28791,Welcome to Marwen,2018,"[Steve Carell, Leslie Mann, Diane Kruger, Falk...","[Fantasy, Drama]"
28792,Holmes and Watson,2018,"[Will Ferrell, John C. Reilly, Rebecca Hall, R...","[Action, Mystery, Comedy]"
28793,On the Basis of Sex,2018,"[Felicity Jones, Armie Hammer, Justin Theroux,...","[Biography, Drama]"
28794,Destroyer,2018,"[Nicole Kidman, Tatiana Maslany, Sebastian Sta...","[Crime, Thriller]"

In [7]:
df.tail(2).shape

(2, 4)